# Generated by Django 6.0.2 on 2026-02-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Imtihon nomi')),
                ('exam_type', models.CharField(choices=[('midterm', 'Oraliq nazorat'), ('final', 'Yakuniy nazorat'), ('practice', 'Mashq test')], max_length=20, verbose_name='Imtihon turi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('duration', models.IntegerField(help_text='Davomiyligi (daqiqalarda)', verbose_name='Davomiyligi')),
                ('total_marks', models.IntegerField(default=100, verbose_name='Umumiy ball')),
                ('passing_marks', models.IntegerField(default=60, verbose_name="O'tish balli")),
                ('start_time', models.DateTimeField(verbose_name='Boshlanish vaqti')),
                ('end_time', models.DateTimeField(verbose_name='Tugash vaqti')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('allowed_groups', models.CharField(blank=True, help_text='Guruhlar (vergul bilan ajrating)', max_length=200, verbose_name='Ruxsat etilgan guruhlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
            ],
            options={
                'verbose_name': 'Imtihon',
                'verbose_name_plural': 'Imtihonlar',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'Jarayonda'), ('completed', 'Yakunlangan'), ('abandoned', 'Tashlab ketilgan')], default='in_progress', max_length=20, verbose_name='Holat')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Boshlangan vaqt')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Yakunlangan vaqt')),
            ],
            options={
                'verbose_name': 'Imtihon urinishi',
                'verbose_name_plural': 'Imtihon urinishlari',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Fan nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
            ],
            options={
                'verbose_name': 'Fan',
                'verbose_name_plural': 'Fanlar',
                'ordering': ['name'],
            },
        ),
    ]
