# Generated by Django 6.0.2 on 2026-02-28 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_initial'),
        ('users', '0002_studentgroup_alter_customuser_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='allowed_groups',
            field=models.CharField(blank=True, help_text='Guruhlar (vergul bilan ajrating) — eski usul', max_length=200, verbose_name='Ruxsat etilgan guruhlar (eski)'),
        ),
        migrations.CreateModel(
            name='ExamAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_deadline', models.DateTimeField(help_text='Admin belgilagan oxirgi muddat', verbose_name='Admin deadline')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Biriktirilgan vaqti')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_assignments_made', to=settings.AUTH_USER_MODEL, verbose_name='Biriktirgan admin')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='exams.exam', verbose_name='Imtihon')),
                ('teacher', models.ForeignKey(limit_choices_to={'user_type': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_exams', to=settings.AUTH_USER_MODEL, verbose_name="O'qituvchi")),
            ],
            options={
                'verbose_name': 'Imtihon tayinlanishi',
                'verbose_name_plural': 'Imtihon tayinlanishlari',
                'ordering': ['-created_at'],
                'unique_together': {('exam', 'teacher')},
            },
        ),
        migrations.CreateModel(
            name='ExamGroupPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateTimeField(help_text='Guruh uchun oxirgi muddat', verbose_name='Deadline')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ruxsat berilgan vaqti')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_permissions', to='exams.exam', verbose_name='Imtihon')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_permissions', to='users.studentgroup', verbose_name='Guruh')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_permissions', to=settings.AUTH_USER_MODEL, verbose_name="Ruxsat bergan o'qituvchi")),
            ],
            options={
                'verbose_name': 'Guruh ruxsati',
                'verbose_name_plural': 'Guruh ruxsatlari',
                'ordering': ['-created_at'],
                'unique_together': {('exam', 'group')},
            },
        ),
    ]
