# Generated by Django 6.0.2 on 2026-02-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_alter_exam_allowed_groups_examassignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examassignment',
            name='admin_start_time',
            field=models.DateTimeField(blank=True, help_text='Admin belgilagan ruxsat boshlanish vaqti', null=True, verbose_name='Ruxsat boshlanish vaqti'),
        ),
        migrations.AlterField(
            model_name='examassignment',
            name='admin_deadline',
            field=models.DateTimeField(help_text='Admin belgilagan oxirgi muddat', verbose_name='Ruxsat tugash vaqti'),
        ),
    ]
